import { z } from "zod";

export const discordActions = [
  // Channels
  "get_channel", "modify_channel", "delete_channel",
  // Messages
  "send_message", "get_message", "edit_message", "delete_message",
  "bulk_delete_messages",
  "get_channel_messages", "get_pinned_messages",
  "pin_message", "unpin_message", "crosspost_message",
  // Reactions
  "get_reactions", "create_reaction", "delete_own_reaction",
  "delete_user_reaction", "clear_reactions",
  // Threads
  "create_thread", "join_thread", "leave_thread",
  "add_thread_member", "remove_thread_member", "get_thread_member",
  "list_thread_members", "list_active_threads",
  "list_public_archived_threads", "list_private_archived_threads",
  "list_joined_archived_threads",
  // Guilds
  "get_guild", "get_guild_preview", "modify_guild",
  "get_guild_prune_count", "begin_guild_prune",
  "get_guild_voice_regions", "get_guild_invites", "get_guild_widget",
  "get_guild_vanity_url", "get_guild_welcome_screen",
  "update_guild_welcome_screen", "get_guild_onboarding", "update_guild_onboarding",
  // Members
  "get_member", "list_members", "search_members", "modify_member",
  "add_member_role", "remove_member_role", "kick_member",
  "get_bans", "get_ban", "create_ban", "remove_ban",
  // Users
  "get_user", "get_current_user",
  // Roles
  "get_roles", "create_role", "modify_role", "modify_role_positions", "delete_role",
  // Webhooks
  "get_channel_webhooks", "get_guild_webhooks",
  "create_webhook", "modify_webhook", "delete_webhook", "execute_webhook",
  // Invites
  "get_channel_invites", "create_invite", "delete_invite",
  // Scheduled Events
  "list_scheduled_events", "create_scheduled_event",
  "get_scheduled_event", "modify_scheduled_event",
  "delete_scheduled_event", "get_scheduled_event_users",
  // Emojis
  "get_emojis", "get_emoji", "create_emoji", "modify_emoji", "delete_emoji",
  // Stickers
  "get_stickers", "get_sticker", "create_sticker", "modify_sticker", "delete_sticker",
  // Auto Moderation
  "list_auto_mod_rules", "get_auto_mod_rule",
  "create_auto_mod_rule", "modify_auto_mod_rule", "delete_auto_mod_rule",
  // Stage Instances
  "create_stage_instance", "get_stage_instance",
  "modify_stage_instance", "delete_stage_instance",
  // Application Commands
  "get_global_commands", "create_global_command",
  "get_guild_commands", "create_guild_command", "bulk_overwrite_commands",
  // Audit Log
  "get_audit_log",
] as const;

export const partialDiscordSchema = z.object({
  action: z.enum(discordActions).optional(),
  channelId: z.string().optional(),
  guildId: z.string().optional(),
  messageId: z.string().optional(),
  userId: z.string().optional(),
  roleId: z.string().optional(),
  emoji: z.string().optional(),
  webhookId: z.string().optional(),
  webhookToken: z.string().optional(),
  applicationId: z.string().optional(),
  commandId: z.string().optional(),
  stickerId: z.string().optional(),
  emojiId: z.string().optional(),
  scheduledEventId: z.string().optional(),
  ruleId: z.string().optional(),
  inviteCode: z.string().optional(),
  eventId: z.string().optional(),
  stickerIds: z.string().optional(),
  content: z.string().optional().nullable(),
  tts: z.boolean().optional(),
  embeds: z.string().optional().nullable(),
  allowedMentions: z.string().optional().nullable(),
  messageReference: z.string().optional().nullable(),
  components: z.string().optional().nullable(),
  poll: z.string().optional(),
  flags: z.number().optional(),
  nonce: z.string().optional(),
  enforceNonce: z.boolean().optional(),
  username: z.string().optional(),
  avatarUrl: z.string().optional(),
  threadId: z.string().optional(),
  threadName: z.string().optional(),
  appliedTags: z.string().optional(),
  wait: z.boolean().optional(),
  name: z.string().optional(),
  type: z.number().optional(),
  topic: z.string().optional(),
  position: z.number().optional(),
  parentId: z.string().optional(),
  nsfw: z.boolean().optional(),
  rateLimitPerUser: z.number().optional(),
  permissionOverwrites: z.string().optional(),
  autoArchiveDuration: z.number().optional(),
  invitable: z.boolean().optional(),
  query: z.string().optional(),
  limit: z.number().optional(),
  before: z.string().optional(),
  after: z.string().optional(),
  around: z.string().optional(),
  returnAll: z.boolean().optional(),
  maxItems: z.number().optional(),
  reason: z.string().optional(),
  nick: z.string().optional(),
  roles: z.string().optional(),
  mute: z.boolean().optional(),
  deaf: z.boolean().optional(),
  communicationDisabledUntil: z.string().optional(),
  deleteMessageSeconds: z.number().optional(),
  days: z.number().optional(),
  computePruneCount: z.boolean().optional(),
  includeRoles: z.string().optional(),
  withCounts: z.boolean().optional(),
  withUserCount: z.boolean().optional(),
  image: z.string().optional(),
  description: z.string().optional(),
  tags: z.string().optional(),
  color: z.number().optional(),
  hoist: z.boolean().optional(),
  mentionable: z.boolean().optional(),
  icon: z.string().optional(),
  unicodeEmoji: z.string().optional(),
  scheduledStartTime: z.string().optional(),
  scheduledEndTime: z.string().optional(),
  entityType: z.number().optional(),
  entityMetadata: z.string().optional(),
  privacyLevel: z.number().optional(),
  status: z.number().optional(),
  eventType: z.number().optional(),
  triggerType: z.number().optional(),
  triggerMetadata: z.string().optional(),
  actions: z.string().optional(),
  exemptRoles: z.string().optional(),
  exemptChannels: z.string().optional(),
  enabled: z.boolean().optional(),
  options: z.string().optional(),
  defaultMemberPermissions: z.string().optional(),
  dmPermission: z.boolean().optional(),
  commands: z.string().optional(),
  actionType: z.number().optional(),
  rolePositions: z.string().optional(),
  eventId: z.string().optional(),
  commandType: z.number().optional(),
  withMember: z.boolean().optional(),
  maxAge: z.number().optional(),
  maxUses: z.number().optional(),
  temporary: z.boolean().optional(),
  targetType: z.number().optional(),
  targetUserId: z.string().optional(),
  targetApplicationId: z.string().optional(),
  messageIds: z.string().optional(),
  avatar: z.string().optional(),
  defaultChannelIds: z.string().optional(),
  descriptionLocalizations: z.string().optional(),
  nameLocalizations: z.string().optional(),
  files: z.string().optional(),
  mode: z.string().optional(),
  permissions: z.string().optional(),
  prompts: z.string().optional(),
  unique: z.boolean().optional(),
  webhookChannelId: z.string().optional(),
  welcomeChannels: z.string().optional(),
  withLocalizations: z.boolean().optional(),
});

/** Alias used by the tool factory and index */
export const discordSchema = partialDiscordSchema;
