import { register } from "./registry";
import { createModelTool } from "./tools/model";
import { createReadFileTool, createWriteFileTool, createReadAndUpdateFileTool } from "./tools/fileSystem";
import { createSearchTool } from "./tools/search";
import { createWebscraperTool } from "./tools/webscraper";
import { createMemoryTool } from "./tools/memory";
import { createEmbeddingTool } from "./tools/embedding";
import { createVectorDBTool } from "./tools/vectorDB";
import { createRetrieverTool } from "./tools/retriever";
import { createImageGeneratorTool } from "./tools/imageGeneration";
import { createImageReaderTool } from "./tools/imageReader";
import { createImageEditorTool } from "./tools/imageEditor";
import { createSheetTool, createReadSheetTool } from "./tools/sheets";
import { createCalendarTool } from "./tools/calendar";
import { createEmailTool } from "./tools/email";
import { createChartTool } from "./tools/charts";
import { createPostgresTool, createMySQLTool, createMongoDBTool } from "./tools/database";

register({ nodeRegistry: "model", factory: createModelTool, category: "ai", label: "Model", description: "Call an LLM for reasoning and generation", icon: "brain" });
register({ nodeRegistry: "search", factory: createSearchTool, category: "data", label: "Search", description: "Google Custom Search web search", icon: "search" });
register({ nodeRegistry: "webscraper", factory: createWebscraperTool, category: "data", label: "Web Scraper", description: "Scrape web pages with Firecrawl", icon: "globe" });
register({ nodeRegistry: "memory", factory: createMemoryTool, category: "storage", label: "Memory", description: "Persistent key-value memory store", icon: "database" });
register({ nodeRegistry: "embedding", factory: createEmbeddingTool, category: "ai", label: "Embedding", description: "Convert text to vector embeddings", icon: "vector" });
register({ nodeRegistry: "vectorDB", factory: createVectorDBTool, category: "storage", label: "Vector DB", description: "Query and upsert Pinecone vectors", icon: "layers" });
register({ nodeRegistry: "retriever", factory: createRetrieverTool, category: "data", label: "Retriever", description: "Semantic document retrieval", icon: "file-text" });
register({ nodeRegistry: "imageGenerator", factory: createImageGeneratorTool, category: "ai", label: "Image Generator", description: "Generate images with DALL-E 3", icon: "image" });
register({ nodeRegistry: "imageReader", factory: createImageReaderTool, category: "ai", label: "Image Reader", description: "Analyze images with GPT-4o vision", icon: "eye" });
register({ nodeRegistry: "imageEditor", factory: createImageEditorTool, category: "ai", label: "Image Editor", description: "Edit images with DALL-E 2 inpainting", icon: "edit" });
register({ nodeRegistry: "sheet", factory: createSheetTool, category: "integration", label: "Sheet", description: "Write data to Google Sheets", icon: "table" });
register({ nodeRegistry: "readSheet", factory: createReadSheetTool, category: "integration", label: "Read Sheet", description: "Read data from Google Sheets", icon: "table" });
register({ nodeRegistry: "calendarEvent", factory: createCalendarTool, category: "integration", label: "Calendar", description: "Create Google Calendar events", icon: "calendar" });
register({ nodeRegistry: "sendMail", factory: createEmailTool, category: "communication", label: "Send Mail", description: "Send emails via SMTP", icon: "mail" });
register({ nodeRegistry: "chart", factory: createChartTool, category: "utility", label: "Chart", description: "Generate pie/line charts via QuickChart", icon: "bar-chart" });
register({ nodeRegistry: "readFile", factory: createReadFileTool, category: "utility", label: "Read File", description: "Read files from project workspace", icon: "file" });
register({ nodeRegistry: "writeFile", factory: createWriteFileTool, category: "utility", label: "Write File", description: "Write files to project workspace", icon: "file-plus" });
register({ nodeRegistry: "readAndUpdateFile", factory: createReadAndUpdateFileTool, category: "utility", label: "Edit File", description: "Find-replace content in a file", icon: "file-edit" });
register({ nodeRegistry: "postgresDB", factory: createPostgresTool, category: "storage", label: "PostgreSQL", description: "Query a PostgreSQL database with your credentials", icon: "database" });
register({ nodeRegistry: "mysqlDB", factory: createMySQLTool, category: "storage", label: "MySQL", description: "Query a MySQL database with your credentials", icon: "database" });
register({ nodeRegistry: "mongoDB", factory: createMongoDBTool, category: "storage", label: "MongoDB", description: "Query a MongoDB database with your connection URI", icon: "database" });

export { register, build, list, getRegistration } from "./registry";
export type { ToolFactory, ToolRegistration, ToolCategory } from "./types";
